name: Update Localization Files

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # Runs twice a day

jobs:
  update-localization:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo A Fork
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: 'ao-bin-dumps'

    - name: Check for Changes in localization.json
      run: |
        cd ao-bin-dumps
        git fetch origin master
        # For testing, we're setting CHANGES_DETECTED to true directly
        echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
        # CHANGED_FILES=$(git diff --name-only FETCH_HEAD $(git rev-parse HEAD) | grep 'localization.json' || true)
        # if [ -n "$CHANGED_FILES" ]; then
        #   echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
        # else
        #   echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
        # fi

    - name: Setup jq
      if: env.CHANGES_DETECTED == 'true'
      run: sudo apt-get install jq

    - name: Perform JSON Manipulation
      if: env.CHANGES_DETECTED == 'true'
      run: |
        cd ao-bin-dumps
        jq "[.tmx.body.tu[] | select(.\"@tuid\" | startswith(\"@ITEMS_\")) | .[\"@tuid\"] |= sub(\"@\"; \"\")]" localization.json > items_localization.json
        jq "[.tmx.body.tu[] | select(.\"@tuid\" | startswith(\"@MARKETPLACEGUI_ROLLOUT_SHOPCATEGORY_\")) | .[\"@tuid\"] |= sub(\"^@MARKETPLACEGUI_ROLLOUT_\"; \"\")]" localization.json > shopcategory_localization.json
        jq "[.tmx.body.tu[] | select(.\"@tuid\" | startswith(\"@MARKETPLACEGUI_ROLLOUT_SHOPSUBCATEGORY_\")) | .[\"@tuid\"] |= sub(\"^@MARKETPLACEGUI_ROLLOUT_\"; \"\")]" localization.json > shopsubcategory_localization.json
        jq "[.tmx.body.tu[] | select(.\"@tuid\" | startswith(\"@DESTINYBOARD_\")) | .[\"@tuid\"] |= sub(\"@\"; \"\")]" localization.json > destinyboard_localization.json
        jq -s ".[0] + .[1] + .[2] + .[3]" items_localization.json shopcategory_localization.json shopsubcategory_localization.json destinyboard_localization.json > merged_localization.json

    - name: Checkout Repo B
      if: env.CHANGES_DETECTED == 'true'
      uses: actions/checkout@v2
      with:
        repository: 'JPCodeCraft/AlbionLocalization'
        token: ${{ secrets.ALBIONLOCALIZATION }}
        path: 'AlbionLocalization'

    - name: Copy Files to Repo B
      if: env.CHANGES_DETECTED == 'true'
      run: |
        cp ao-bin-dumps/*.json AlbionLocalization/

    - name: Commit and Push to Repo B
      if: env.CHANGES_DETECTED == 'true'
      run: |
        cd AlbionLocalization
        git config --global user.email "albionfreemarket@gmail.com"
        git config --global user.name "Albion Free Market"
        git add .
        git commit -m "Update localization files"
        git push
